BIN_DIR=bin
LOG_DIR=logs
TCP_PORT=9000
NATS_CONTAINER=nats

.PHONY: init build nats-up nats-down kill start stop restart logs test clean

init:
	@mkdir -p $(BIN_DIR)
	@mkdir -p $(LOG_DIR)

# -----------------------
# BUILD
# -----------------------
build: init
	@echo "🔨 Building binaries..."
	@go build -o $(BIN_DIR)/tcp-server cmd/tcp-server/main.go
	@go build -o $(BIN_DIR)/consumer cmd/consumer/main.go
	@go build -o $(BIN_DIR)/simulator simulator/main.go
	@echo "✅ Build complete"

# -----------------------
# NATS
# -----------------------
nats-up:
	@docker run -d --name $(NATS_CONTAINER) -p 4222:4222 nats || true

nats-down:
	@docker stop $(NATS_CONTAINER) || true
	@docker rm $(NATS_CONTAINER) || true

# -----------------------
# PROCESS CONTROL
# -----------------------
kill:
	@lsof -ti tcp:$(TCP_PORT) | xargs -r kill -9

# -----------------------
# RUN SERVICES
# -----------------------
start: nats-up build
	@echo "🚀 Starting TCP server..."
	@nohup ./$(BIN_DIR)/tcp-server > $(LOG_DIR)/tcp.log 2>&1 &
	@echo "📥 Starting Consumer..."
	@nohup ./$(BIN_DIR)/consumer > $(LOG_DIR)/consumer.log 2>&1 &
	@echo "✅ Services running"

restart: stop start

test: build
	@echo "🚗 Starting simulator..."
	@nohup ./$(BIN_DIR)/simulator > $(LOG_DIR)/simulator.log 2>&1 &

logs:
	@tail -f $(LOG_DIR)/tcp.log $(LOG_DIR)/consumer.log $(LOG_DIR)/simulator.log

stop:
	@pkill tcp-server || true
	@pkill consumer || true
	@pkill simulator || true
	@make nats-down
	@echo "🛑 All stopped"

clean:
	@rm -rf $(BIN_DIR) $(LOG_DIR)
